# Generated by Django 5.0.1 on 2024-06-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('analytics', 'Analytics'), ('desenvolvimento', 'Desenvolvimento'), ('gestao', 'Gestão')], max_length=50)),
                ('profissional', models.CharField(choices=[('desenvolvedor', 'Desenvolvedor'), ('analista_dados', 'Analista de Dados')], max_length=50)),
                ('senioridade', models.CharField(choices=[('junior', 'Junior'), ('pleno', 'Pleno'), ('senior', 'Senior'), ('especialista', 'Especialista'), ('coordenador', 'Coordenador'), ('tech_lead', 'Tech Lead')], max_length=50)),
                ('forma_pagamento', models.CharField(choices=[('pre_pago', 'Pré Pago'), ('30_dias', '30 dias'), ('60_dias', '60 dias'), ('90_dias', '90 dias')], max_length=50)),
                ('margem', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
        ),
    ]
