# Generated by Django 5.0.1 on 2024-07-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentoComercial', '0003_alter_orcamentocomercial_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentocomercial',
            name='profissional',
            field=models.CharField(choices=[('desenvolvedor', 'Desenvolvedor'), ('analista_dados', 'Analista de Dados')], max_length=40),
        ),
    ]
