# Generated by Django 5.0.1 on 2024-07-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentoComercial', '0005_cargo_remove_orcamentocomercial_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentocomercial',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentoComercial.cargo'),
        ),
    ]
