# Generated by Django 5.0.1 on 2024-07-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentoComercial', '0006_alter_orcamentocomercial_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='cargo',
            name='senioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentoComercial.senioridade'),
        ),
    ]
