# Generated by Django 5.0.1 on 2024-07-05 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentoComercial', '0007_senioridade_alter_cargo_senioridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='orcamentocomercial',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentoComercial.pagamento'),
        ),
    ]
