# Generated by Django 5.0.1 on 2024-07-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentoComercial', '0008_pagamento_alter_orcamentocomercial_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='orcamentocomercial',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentoComercial.area'),
        ),
    ]
