# Generated by Django 5.0.1 on 2024-07-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentoComercial', '0009_area_alter_orcamentocomercial_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
