# Generated by Django 5.0.1 on 2024-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentoComercial', '0010_alter_cargo_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentocomercial',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
